# action.yml
name: 'Discord Webhook Action'
description: 'Send custom messages or upload files to discord webhooks with simple action inputs.'
branding:
  icon: message-square
  color: purple
inputs:
  webhook-url:
    description: 'Webhook URL from discord. See: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks for details'
    required: true
  content:
    description: 'Message that is sent via the webhook.'
    required: true
  username: 
    description: 'The username that should appear to send the message. Note: username will have the "bot" badge next to their name.'
    required: false
  avatar-url:
    description: 'URL for the avatar that should appear with the message.'
    required: false
  raw-data:
    description: 'Name of a json file that will be sent as the data for the webhook'
    required: false
  filename:
    description: 'Name of a file that will be uploaded via the webhook'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -w
    - ${{ inputs.webhook-url }}
    - -c
    - ${{ inputs.content }}
    - -u
    - ${{ inputs.username }}
    - -a
    - ${{ inputs.avatar-url }}
    - -d
    - ${{ inputs.raw-data }}
    - -f
    - ${{ inputs.filename }}
