name: Operating System Compatability Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: v4.0.0
        type: string
        required: false

jobs:
  test-all-os:
    strategy:
      matrix:
        os:
          - windows-latest
          - windows-2022
          - windows2019
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-12
          - macos-11
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@${{ github.event.inputs.version }}
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: Foobar