name: Operating System Compatability Test

on:
  workflow_dispatch:

jobs:
  test-all-os:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - windows-2022
          - windows2019
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-12
          - macos-11
          - macos-10.15
        version:
          - ${{ github.event.inputs.action_version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: ${{ matrix.os }} works!